### ISSUE TITLE
Permissão da conexão por mensagem

### ISSUE THREAD

**Issue by adrianofreires** [evolution-foundation/evolution-manager#1]
Gabriel, primeiro parabéns pelo painel está incrível! 

Mas uma dúvida: Se eu quiser fornecer isso para o cliente, ele precisa estar do meu lado para poder escanear? Ou eu tiro um print do QRCode e ele escaneia por lá?

Teria como fazer algo para enviar um código por mensagem?

Obrigado mais uma vez

**Comment by gabrielpastori1** [comment]
Boa tarde, obrigado, por enquanto esse painel é apenas para o gerenciamento, no futuro planjo desenvolver um com gerenciamento de usuário, no momento o que posso fazer é colocar um botão para salvar o QRCode como imagem, porem você terá que enviar para a pessoa rápido, antes que eles espire.
