### ISSUE TITLE
Inclusão de campos na configuração do Chatwoot

### ISSUE THREAD

**Issue by cbalbinos** [evolution-foundation/evolution-manager#2]
Gabriel,

Primeiramente parabéns pelo belissimo projeto!

Seria útil adicionar os campos **nome da instancia** e **webhook url** na configuração do Chatwoot, como ocorre no modelo do Manager oferecido pela Evolution

![chatwoot](https://github.com/gabrielpastori1/evolution-manager/assets/91399681/ceb63826-5e8d-4315-9de3-5bae868ad87f)

**Comment by gabrielpastori1** [comment]
Será adicionado na próxima atualização

**Comment by gabrielpastori1** [comment]
![image](https://github.com/gabrielpastori1/evolution-manager/assets/58153955/434c339c-6828-4117-b604-505b43d59845)
Acabei de adicionar essa informação junto com um pequeno tutorial de como configurar o chatwoot

**Comment by gabrielpastori1** [comment]
https://github.com/gabrielpastori1/evolution-manager/commit/6567fc7db0e406de85648d7a019db20e3c867750

**Comment by cbalbinos** [comment]
Ficou ótimo! 👏🚀

**Comment by cbalbinos** [comment]
Em breve vou gravar um conteúdo sobre seu projeto para meu canal do YouTube. 

Parabéns novamente pelo belissimo projeto!
