### ISSUE TITLE
Gerar Link do QR Code

### ISSUE THREAD

**Issue by luisflpstos** [evolution-foundation/evolution-manager#6]
Gostaria de saber a possibilidade de adicionar um gerador de link de QR code para ser enviado com botão de atualizar neste link, assim poderia enviar para clientes ou pessoas sem a necessidade de passar o acesso ao manager.

**Comment by gabrielpastori1** [comment]
Infelizmente no momento não é possível pois teria que compartilhar as informações como URL e API Key, sem um backend não tem como fazer isso de forma segura
